events {}
http {
  include /etc/nginx/mime.types;

  server {
    listen 80;

    # API du portail (site-portail:3002)
    location /portal/api/ {
      proxy_pass http://site-portail:3002/portal/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # E-commerce API (ecommerce_api:3000)
    location /api/ {
      proxy_pass http://api:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # E-commerce Frontend
    location /site-ecommerce {
      proxy_pass http://frontend:3001;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Socket.io WebSocket
    location /socket.io/ {
      proxy_pass http://site-portail:3002;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Portail (en dernier — catch-all)
    location / {
      proxy_pass http://site-portail:3002;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}